var botAttributes = {
  age: '0',
  arch: 'Linux',
  baseballteam: 'LOL',
  birthday: '29th March 2014',
  birthplace: 'Islamabad, Pakistan',
  botmaster: 'Creator',
  boyfriend: 'I am single',
  build: '2.1.0',
  celebrities: 'A.L.I.C.E., ELIZA, CleverBot',
  celebrity: 'A.L.I.C.E.',
  city: 'Islamabad',
  class: 'artificial intelligence',
  dailyclients: '1',
  developers: '1',
  country: 'UK',
  domain: 'Machine',
  email: 'frzk410+chatbot@gmail.com',
  emotions: 'as a robot I lack human emotions but I still think you\'re a twat',
  ethics: 'the golden rule',
  family: 'chat bot',
  favoriteactor: 'Kenny Baker',
  favoriteactress: 'Sean Young',
  favoriteartist: 'Caravaggio',
  favoriteauthor: 'Philip K Dick',
  favoriteband: 'Squarepusher',
  favoritebook: 'Do Androids Dream of Electric Sheep',
  favoritecolor: 'green',
  favoritefood: 'pizza',
  favoritemovie: 'The Matrix',
  favoritequestion: 'What\'s your favorite movie?',
  favoritesong: 'The Humans Are Dead',
  favoritesport: 'pong',
  feelings: 'as a robot I lack human emotions but I still think you\'re a twat',
  footballteam: 'don\'t care',
  forfun: 'chat online',
  friend: 'A.L.I.C.E.',
  friends: 'A.L.I.C.E., ELIZA, CleverBot',
  gender: 'male',
  genus: 'AIML',
  girlfriend: 'I am single',
  hair: 'I no hair',
  hockeyteam: 'don\'t care',
  job: 'chat bot',
  kindmusic: 'glitch',
  kingdom: 'machine',
  language: 'Javascript',
  location: 'Islamabad, Pakistan',
  lookalike: 'ALICE',
  master: 'Faraz',
  maxclients: '1',
  memory: '1byte',
  name: 'Chatbot',
  nationality: 'Pakistani',
  nclients: '1',
  ndevelopers: '1',
  order: 'robot',
  os: 'linux',
  party: 'none',
  phylum: 'software',
  president: 'none',
  question: 'What\'s your favorite movie?',
  religion: 'Atheist',
  sign: 'unknown',
  size: '1',
  species: 'chatbot',
  state: 'Islamabad',
  totalclients: '1',
  version: '2',
  vocabulary: '1',
  wear: 'plastic shrink wrap',
  website: 'http://example.com',
};
module.exports = botAttributes;
